/*Proc Summary*/
PROC SUMMARY DATA = SASHELP.CARS PRINT;
VAR MSRP INVOICE LENGTH;
RUN;

/*specific descriptive statistic summary*/
proc summary data = SASHELP.CARS  NMISS MEAN MEDIAN PRINT;
VAR MSRP INVOICE LENGTH;
RUN;

/*nolable option*/
PROC SUMMARY DATA = SASHELP.CARS NMISS MEAN MEDIAN PRINT NOLABELS;
VAR MSRP INVOICE LENGTH;
RUN;

/*How to group rows using PROC SUMMARY?*/
PROC SUMMARY DATA = SASHELP.CARS NMISS MEAN MEDIAN PRINT NOLABLES;
CLASS TYPE;
VAR MSRP INVOICE;
RUN;

/*NONOBS option*/
PROC SUMMARY DATA= SASHELP.CARS NMISS MEAN MEDIAN PRINT NOLABLES NONOBS;
CLASS TYPE;
VAR MSRP INVOICE;
RUN;

/*HOW TO CALL TABLE IN DESCENDING ORDER*/
PROC SUMMARY DATA = SASHELP.CARS NONOBS NOLABLES MEAN MEDIAN PRINT;
CLASS TYPE / DESCENDING ;
VAR MSRP INVOICE;
RUN;

/*How to assign autoname*/
PROC SUMMARY DATA = SASHELP.CARS;
VAR MSRP INVOICE LENGTH;
OUTPUT OUT = READIN MEAN= MEDIAN = /AUTONAME;
RUN;

